# Generated by Django 4.1.4 on 2023-05-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_is_delivered_alter_order_delivery_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_delivered",
            field=models.BooleanField(default=False, verbose_name="وضعیت تحویل"),
        ),
    ]
